#!/usr/bin/env bash

cd "$(dirname "$0")"
. "./.common.sh"
cd ..

PATH="$(pwd)/sandbox/composer/bin:$PATH"

if ! chkcmd 'apigen'; then
        echo ' error: "apigen" command not found.'
        echo ' Execute "./support/init" first.'
        exit 1
fi

api_dir="doc/api"

if test -d "$api_dir"; then
        rm -rf "$api_dir"
fi

genapi() {
        apigen generate                         \
                --source "source"               \
                --destination "$api_dir"        \
                --template-theme bootstrap      \
                --template-config "./sandbox/composer/apigen/theme-bootstrap/src/config.neon" \
                --title "FluidXML"              \
                --todo                          \
                --tree                          \
                --debug
}

doc_handler()
{
        genapi || true

        while read -d '' e; do
                clear
                genapi || true
        done
}

genapi

echo "Open $api_dir/index.html"

watch "source/" | dsstore_filter | doc_handler
