#!/usr/bin/env sh

cd "$(dirname "$0")"
. ".common.sh"
cd ../..

PATH="sandbox/composer/bin:$PATH"

if ! chkcmd 'peridot'; then
        echo ' error: "peridot" command not found.'
        echo ' Execute "./support/tools/init" first.'
        exit 1
fi

if ! chkcmd 'phpdbg'; then
        echo ' error: "phpdbg" command not found.'
        exit 1
fi

phpdbg -e "$(which peridot)" -c "support/peridot.php" -r html-code-coverage -g "*.php" "specs/"

## Type:
## run
## quit

chkcmd 'open' && open "code-coverage-report/index.html"
