#!/usr/bin/env sh

cd "$(dirname "$0")"
. "./.common.sh"
cd ../..

PATH="$(pwd)/sandbox/composer/bin:$PATH"

if ! chkcmd 'peridot'; then
        echo ' error: "peridot" command not found.'
        echo ' Execute "./support/tools/init" first.'
        exit 1
fi

cd sandbox

peridot_arguments='-c "../support/peridot.php" -r html-code-coverage -g "*.php" "../specs/"'

if chkcmd 'phpdbg'; then
        echo ' type: run'
        echo '       quit'
        echo

        eval "phpdbg -e \"$(which peridot)\" $peridot_arguments"
else
        echo ' info: "phpdbg" command not found.'

        eval "peridot $peridot_arguments"
fi

chkcmd 'open' && open "code-coverage-report/index.html"
