#!/usr/bin/env sh

cd "$(dirname "$0")"
. ".common.sh"
cd ../..

PATH="sandbox/composer/bin:$PATH"

if ! chkcmd 'phpdoc'; then
        echo ' error: "phpdoc" command not found.'
        echo ' Execute "./bin/init" first.'
        exit 1
fi


phpdoc -d "source" -t "documents/api" --template clean
