#!/usr/bin/env sh

cd "$(dirname "$0")"
. "./.common.sh"
cd ../..

if ! chkcmd 'composer'; then
        echo ' error: "composer" command not found.'
        exit 1
fi

mkdir -pv "sandbox"
mkdir -pv "sandbox/composer"

composer install -d "." --no-interaction
rm -f "./composer.lock"
