#!/usr/bin/env sh

cd "$(dirname "$0")"
. "./.common.sh"
cd ../..

tester="./support/tools/test"

if ! chkcmd 'brew'; then
        echo ' "brew" command not found.'
        echo ' Skipping version based testing for PHP {8.1, 8.2}.'

        "$tester"
else
        brew unlink php@8.1 > /dev/null     \
        && brew link php@8.1      > /dev/null     \
        && printf "\nTesting against PHP 8.1\n" \
        && "$tester"                            \
        && clear                                \
        && brew unlink php@8.1    > /dev/null     \
        && brew link php@8.2      > /dev/null     \
        && printf "\nTesting against PHP 8.2\n" \
        && "$tester"
fi
