#!/usr/bin/env sh

cd "$(dirname "$0")"
. "./.common.sh"
cd ../..

PATH="$(pwd)/sandbox/composer/bin:$PATH"

if ! chkcmd 'peridot'; then
        echo ' error: "peridot" command not found.'
        echo ' Execute "./support/tools/init" first.'
        exit 1
fi

peridot -g "*.php" "./specs/"
